article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addarticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addComment,name="comment"),
]

blog1/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/', views.about,name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "user"

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):       
    author = models.ForeignKey("auth.User",on_delete= models.CASCADE,verbose_name="İstifadəçi adı")#vorbose_name default ingisilce ad yox dirnaq icinde yazdigimiz sozun cixmasi ucundur
    title = models.CharField(max_length= 50,verbose_name="Başlıq")
    content = RichTextField(verbose_name="Mətn")
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Yaranma Tarixi")
    article_image = models.FileField(blank=True,null=True,verbose_name="Məqaləyə Şəkil yükləyin")
    def __str__(self):
        return self.title #bu kod bizim cedvelimizde title'da basanda article'mizin acilmagina komek edir
    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Məqalə",related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="Ad")
    comment_content = models.CharField(max_length=200,verbose_name="Şərh")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article,Comment
from django.contrib.auth.decorators import login_required
# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})
def index(request):
    #return HttpResponse("<h1>Əsas Səhifə</h1>")#
    return render(request,"index.html")
def about(request):
    return render(request,"about.html")
@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url = "user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Məqalə uğurla yükləndi...")
        return redirect("index")
    return render(request,"addarticle.html",{"form":form})
def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})
@login_required(login_url = "user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance= article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Məqalə uğurla yeniləndi...")
        return redirect("article:dashboard")
    return render(request,"update.html",{"form":form})
@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance= article)
    if form.is_valid():
        
        article.author = request.user
        article.delete()
        messages.success(request,"Məqalə uğurla silindi...")
        return redirect("article:dashboard")
    return render(request,"delete.html",{"form":form})
    #article.delete()
    #messages.success(request,"Məqalə uğurla silindi...")
    #return redirect("article:dashboard")
def addComment(request,id):
    article = get_object_or_404(Article,id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author,comment_content = comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))



    

templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>Haqqımızda</h3>
<hr>
<p>Haqqımızda qismindən hər kəsə salam.Mən Kərimli Abduləziz,mən Azərbaycan Memarlıq və İnşaat Universiteti'nin MİT fakültəsində təhsil alıram və bu səhifə mənim tərfimdən yaradılıb.
<br>
Əlaqə:karimliabdulaziz5@gmail.com
</p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <style>
        h3{
        border:2px solid rgb(32, 32, 32);
        border-radius: 3px;
        background-color: rgb(32, 32, 32);
        color:white;
        text-align: center;
        }
        .btn-danger:hover{
        border:yellowgreen;
        background-color: yellowgreen;
        color:black
        }
    </style>
    <h3>Məqalə yüklə</h3>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{form|crispy}}
        <button type="submit" class = "btn btn-danger">Məqalə yüklə</button>
    </form>
  </div>
</div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
<div class="row">
  <div class="col-md-10 offset-md-3">
    <div class="col-lg-8">
<style>
#first{
        border:2px solid rgb(32, 32, 32);
        border-radius: 3px;
        background-color: rgb(32, 32, 32);
        color:white;
        text-align: center;
}
#firsta{
    color:black;
}
#firsta:hover{
    color:rgb(19, 35, 250);
}
.btn-danger:hover{
  border:yellowgreen;
  background-color: yellowgreen;
  color:black
}
input{
  border:1px solid black;
  border-radius: 4px;
  height: 37px;
}



</style>
<h3 id="first">Məqalələr</h3>
<hr>
</div>
</div>
</div>
<div class="row">
  <div class="col-md-10 offset-md-3">
    <div class="col-lg-8">
    
      <form>
        {% csrf_token %}
        <input type="text" name="keyword" class=" input-sm" maxlength="64" placeholder="Axtarış">
        <button type="submit" class="btn btn-danger">Axtarış</button>
      </form>
    </div>
  </div>
    
</div>

{% if articles %}

{% for article in articles %}
    <div class="row">
    <div class="col-md-10 offset-md-3">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <a id="firsta" href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a>
        <!-- Author -->
        <p class="lead">
          {{article.author.username}} tərəfindən daxil edildi.
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
        {% endif %}
        

        <hr>

        <!-- Post Content -->
        <p class="lead">
            {{article.content|safe|truncatewords:30}}
        </p>
        <a style="float : right;" href="{% url 'article:detail' article.id %}" class="btn btn-danger">Davamını oxu</a>
        <hr>

        

       

        

      </div>
    

      

        

        
        

      
    </div>
    </div>

{% endfor %}

{% else %}
<div class="row">
  <div class="col-md-10 offset-md-3">
    <div class="col-lg-8">
      <div style="margin-top:5px;"class="alert alert-danger">
        Məqalə tapılmadı
      </div>
    </div>
  </div>
</div>      
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Nəzarət paneli</h3>
<hr>
<p>
Xoş gəldiniz,<small>{{request.user.username}}</small>
</p>
<hr>
<a class="btn btn-danger" href="{% url 'article:addarticle' %}">Məqalə yüklə</a>
<hr>
{% if articles %}
<style>
    table{
        border-radius:6px
        
    }
    a{
        color:black;
        text-decoration: none;
        border: none;
    }
    a:hover{
        color:red
    }
</style>
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Başlıq</th>
      <th scope="col">Yazıçı</th>
      <th scope="col">Tarix</th>
      <th scope="col">Yenilə</th>
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td><a href="{% url 'article:update' article.id %}" class="btn btn-danger">Yenilə</a></td>
      <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
    </tr>
    {% endfor %}
    
</table>
{% else %}
<div class="alert alert-danger">
 Hal hazırda sizin hər hansısa bir məqaləniz yoxdur,məqalə yükləmək üçün "Məqalə yüklə" düymısini sıxın...
</div>
{% endif %}

{% endblock body %}

templates/delete.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <style>
        h3{
        border:2px solid rgb(32, 32, 32);
        border-radius: 3px;
        background-color: rgb(32, 32, 32);
        color:white;
        text-align: center;
        }
        .btn-danger:hover{
        border:yellowgreen;
        background-color: yellowgreen;
        color:black
        }
    </style>
    <h3>Məqalə sil</h3>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{form|crispy}}
        <h4>Bu məqaləni silməyə əminsinizmi?</h4>
        <p><input type="submit" value="Bəli" class="btn btn-danger"> <a href="{% url 'article:dashboard' %}" class="btn btn-danger">Xeyr</a></p>
    </form>
  </div>
</div>
{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<style>
  .btn-danger:hover{
    border:yellowgreen;
    background-color: yellowgreen;
    color:black
}
</style>
<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h3 class="mt-4">{{article.title}}</h3>
        <!-- Author -->
        <p class="lead">
          by
          {{article.author.username}}
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        {% endif %}
        

        <hr>

        <!-- Post Content -->
        <p class="lead">
            {{article.content|safe}}
        </p>
        <hr>
        <h4>Şərhlər</h4>
        <hr>
        {% if comments %}
        {% for comment in comments %}
        <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">{{comment.comment_author}}</h5>
          {{comment.comment_date}}<br/>    
          {{comment.comment_content}}
        </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="alert alert-danger">
        Bu məqaləyə hər hansısa bir şərh daxil edilməyib,ilk şərhi siz daxil edin!
        </div>
        {% endif %}
        <div class="card my-4">
          <h5 class="card-header">Şərh daxil edin:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="formGroupExampleInput">Ad:</label>
                  <input name = "comment_author" class="form-control"  placeholder="Adınız">
              </div>
              <div class="form-group">
                <label for="formGroupExampleInput">Şərh:</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Göndər</button>
            </form>
          </div>
        </div>
      </div>
</div>


{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron text-center">
    <h3>Proqramlaşdırma dilləri səhifəsinə xoş gəldiniz</h3>
    <p>Bu səhifədə siz müxtəlif proqramlaşdırma dilləri haqqında məqalələr yazıb bu səhifəyə daxil edib insanlara proqramlaşdırma dilləri haqqında məlumatlar verə bilərsiniz.</p>
</div>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{%load static%}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta  name="keywords" content="Proqramlaşdırma dilləri,Python,Java Script,PHP,Django"/>
    <meta  name="description" content=">Bu səhifədə siz müxtəlif proqramlaşdırma dilləri haqqında məqalələr yazıb bu səhifəyə daxil edib insanlara proqramlaşdırma dilləri haqqında məlumatlar verə bilərsiniz."/>
    <meta  name="author" content="Kərimli Abduləziz"/>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link rel="shortcut icon" type="image/png" href="{% static 'icons8-google-code-64.ico' %}"/>
    <title>Proqramlaşdırma Dilləri</title>
    
</head>
<body>
    {% include "includes/navbar.html" %}
    
    <div style = "margin-top:120px;margin-bottom:100px"class="container">
        {% if messages %}
    
        {% for message in messages %}
        {% if message.tags == "info" %}
        <div class="alert alert-danger">{{ message }}</div>
        {% else %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
        
        {% endfor %}
    
        {% endif %}
        {% block body %}
        
        {% endblock body %}
    </div>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <style>
        h3{
        border:2px solid rgb(32, 32, 32);
        border-radius: 3px;
        background-color: rgb(32, 32, 32);
        color:white;
        text-align: center;
        }
        .btn-danger:hover{
        border:yellowgreen;
        background-color: yellowgreen;
        color:black
        }
        a{
          color:white;
          text-decoration: none;
        }
        a:hover{
          color:black;
          text-decoration: none;
        }
    </style>
    <h3>Giriş et</h3>
    <hr>
    <form method = "post" >
        {% csrf_token %}
        {{form|crispy}}
        <p>Əgər bir hesabınız yoxdursa "Qeydiyyatdan keç"ə basaraq qeydiyyatdan keçə bilərsiniz</p>
        
        <button type="submit" class = "btn btn-danger">Daxil ol</button>
        <button type="submit" class = "btn btn-danger"><a href="{% url 'user:register' %}">Qeydiyyatdan keç</a></button>
    </form>
  </div>
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <style>
    h3{
        border:2px solid rgb(32, 32, 32);
        border-radius: 3px;
        background-color: rgb(32, 32, 32);
        color:white;
        text-align: center;
    }
    .btn-danger:hover{
        border:yellowgreen;
        background-color: yellowgreen;
        color:black
    }
</style>
<h3>Qeydiyyatdan keç</h3>
<hr>

<form  method="post">
    {% csrf_token %}
    {{form|crispy}}
    <p>Qaydalar:Məqalələrdə argo kəlimələr,qeyri-etik şeylər paylaşmaq qadağandır.</p>
    <button type="submit" class="btn btn-danger">Qeydiyyatdan keç</button>
</form>

  </div>
</div>


{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <style>
        h3{
        border:2px solid rgb(32, 32, 32);
        border-radius: 3px;
        background-color: rgb(32, 32, 32);
        color:white;
        text-align: center;
        }
        .btn-danger:hover{
        border:yellowgreen;
        background-color: yellowgreen;
        color:black
        }
    </style>
    <h3>Məqalə yenilə</h3>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{form|crispy}}
        <button type="submit" class = "btn btn-danger">Məqalə yenilə</button>
    </form>
  </div>
</div>
{% endblock body %}